# config.yaml

# Paths
model_to_decode_path: /neurospin/dico/data/deep_folding/current/models/Champollion_V1_after_ablation/CINGULATE_right/name17-24-32_237
dataset_folder: /neurospin/dico/data/deep_folding/current/datasets
train_csv: ukb40_random_embeddings/train_embeddings.csv
val_test_csv: ukb40_random_embeddings/val_embeddings.csv
output_dir: /volatile/ad279118/2025_Champollion_Decoder/deep_learning/evaluation

# Model / training parameters
experiment_name: "3_test"
num_cpu_workers: 10
batch_size: 32
learning_rate: 0.001
num_epochs: 20
dropout: 0.05

# Decoder-specific options
decoder_type: "convnet"    
encoder_depth: 3
block_depth: 4
filters: [128, 64, 32]
last_kernel_size: 7
activation: "relu"