# config.yaml

# Paths
model_to_decode_path: /neurospin/dico/data/deep_folding/current/models/Champollion_V1_after_ablation_latent_256/FIP_left/name08-48-12_141
dataset_folder: /neurospin/dico/data/deep_folding/current/datasets
train_csv: ukb40_random_embeddings/train_embeddings.csv
val_test_csv: ukb40_random_embeddings/val_embeddings.csv
output_dir: /volatile/ad279118/2025_Champollion_Decoder/deep_learning/evaluation

# Model / training parameters
num_cpu_workers: 10
batch_size: 32
loss: mse
learning_rate: 5e-4
num_epochs: 5
dropout: 0.05
save_best_model: true