# config.yaml

# Paths
model_to_decode_path: /neurospin/dico/data/deep_folding/current/models/Champollion_V1_after_ablation/SOr-SOlf_right/name08-22-27_80
dataset_folder: /neurospin/dico/data/deep_folding/current/datasets
train_csv: ukb40_random_embeddings/train_embeddings.csv
val_test_csv: ukb40_random_embeddings/val_embeddings.csv
output_dir: /volatile/ad279118/2025_Champollion_Decoder/deep_learning/evaluation

# Model / training parameters
experiment_name: "6_test_bce_5e-4"
num_cpu_workers: 10
batch_size: 32
loss: bce
learning_rate: 5e-4
num_epochs: 5
dropout: 0.05

# Optional future extensions
resume_checkpoint: null
save_best_model: true