# config.yaml

# Paths
model_to_decode_path: /neurospin/dico/data/deep_folding/current/models/Champollion_V1_after_ablation_latent_256/fronto-parietal_medial_face_right/name12-55-09_160
dataset_folder: /neurospin/dico/data/deep_folding/current/datasets
train_csv: ukb40_random_embeddings/train_embeddings.csv
val_test_csv: ukb40_random_embeddings/val_embeddings.csv
log_dir: runs

# Model / training parameters
num_cpu_workers: 10
batch_size: 32
loss: bce
learning_rate: 5e-4
num_epochs: 10
dropout: 0.05
save_best_model: true

# for multi model
model_to_decode_dir: /neurospin/dico/data/deep_folding/current/models/Champollion_V1_after_ablation_latent_256